#pragma once

namespace xui
{

enum WindowMessage
{
    XUI_WM_NULL = 0,
    XUI_WM_CREATE,
    XUI_WM_CLOSE,
    XUI_WM_DESTROY,
    XUI_WM_SIZE,
    XUI_WM_PAINT,
    XUI_WM_KEYDOWN,
    XUI_WM_KEYUP,
    XUI_WM_CHAR,
    XUI_WM_LBUTTONDOWN,
    XUI_WM_LBUTTONUP,
    XUI_WM_LBUTTONDBLCLK,
    XUI_WM_RBUTTONDOWN,
    XUI_WM_RBUTTONUP,
    XUI_WM_RBUTTONDBLCLK,
    XUI_WM_MBUTTONDOWN,
    XUI_WM_MBUTTONUP,
    XUI_WM_MBUTTONDBLCLK,
    XUI_WM_XBUTTONDOWN,
    XUI_WM_XBUTTONUP,
    XUI_WM_XBUTTONDBLCLK,
    XUI_WM_WHEEL,
    XUI_WM_HWHEEL,
    XUI_WM_SETFOCUS,
    XUI_WM_KILLFOCUS,

    XUI_WM_COUNT,
};

} // namespace xui
